version: '3'

services:

  iris:
    init: true
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 51773:51773
      - 52773:52773
      - 53773:53773
    volumes:
      - ./:/irisdev/app


